# Generated by Django 5.1.7 on 2025-04-01 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_reply'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('bio', models.TextField(max_length=60)),
                ('college', models.CharField(max_length=50)),
                ('skill1', models.CharField(max_length=20)),
                ('skill2', models.CharField(blank=True, max_length=20, null=True)),
                ('skill3', models.CharField(blank=True, max_length=20, null=True)),
                ('skill4', models.CharField(blank=True, max_length=20, null=True)),
                ('experience_projects', models.TextField(max_length=300)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
