# Generated by Django 5.1.7 on 2025-04-02 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_student_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='skill1',
            new_name='skill',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skill2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skill3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skill4',
        ),
    ]
