# Generated by Django 5.1.7 on 2025-04-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_skill1_profile_skill_remove_profile_skill2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='tag',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
