# Generated by Django 5.2 on 2025-04-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_joinproject_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinproject',
            name='text',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
